---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-redis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-redis
    template:
      data:
        redis_pass: "{{ .password }}"
  dataFrom:
    - extract:
        key: redis
