---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: suwayomi
spec:
  chartRef:
    kind: OCIRepository
    name: suwayomi
  interval: 1h
  values:
    controllers:
      suwayomi:
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.1.2056@sha256:6401322ff96b7a8b59640b1d9cd2d4bd1d92fe1ac26e9db30a89466bab5260a5
            env:
              AUTO_DOWNLOAD_EXCLUDE_UNREAD: false
              AUTO_DOWNLOAD_CHAPTERS: true
              BIND_PORT: &port 80
              DOWNLOAD_AS_CBZ: true
              EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
              FLARESOLVERR_ENABLED: true
              FLARESOLVERR_URL: http://flaresolverr.default.svc.cluster.local:8191
              TZ: Europe/Warsaw
              UPDATE_EXCLUDE_UNREAD: false
              UPDATE_EXCLUDE_STARTED: false
              UPDATE_EXCLUDE_COMPLETED: false
              WEB_UI_CHANNEL: preview
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Manga downloader
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: mdi-book-open-page-variant
          gethomepage.dev/name: Suwayomi
          gethomepage.dev/widget.type: suwayomi
          gethomepage.dev/widget.url: "https://{{ .Release.Name }}.janpuc.com"
          gethomepage.dev/pod-selector: app.kubernetes.io/name=suwayomi
          gethomepage.dev/weight: "20"
        hostnames:
          - "{{ .Release.Name }}.janpuc.com"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk
      media:
        type: nfs
        server: bigmouth.internal
        path: /mnt/Vault/Media/Comics
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk/downloads/mangas
