---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: steam
spec:
  chartRef:
    kind: OCIRepository
    name: steam
  interval: 1h
  values:
    controllers:
      steam:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/steam-headless/steam-headless
              tag: debian@sha256:59b509525951fc941979094493af63c1c8a73b23c069b30038108a833800d83b
            env:
              TZ: Europe/Warsaw
              PUID: 1000
              PGID: 1000
              UMASK: 000
              DISPLAY: ":55"
              MODE: "primary"
              ENABLE_SUNSHINE: "true"
              ENABLE_EVDEV_INPUTS: "true"
              SUNSHINE_USER: "admin"
              SUNSHINE_PASS: "changeme"
              LIBVA_DRIVER_NAME: "radeonsi"
              VDPAU_DRIVER: "radeonsi"
              SUNSHINE_ARGS: "--force-encoder=vaapi"
              SUNSHINE_VIDEO_BITRATE: "20000"
            securityContext:
              privileged: true
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 1
              limits:
                amd.com/gpu: 1
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.69.61
        ports:
          http: { port: 8083 }
          sunshine-ui: { port: 47990, protocol: TCP }
          sun-t1: { port: 47984, protocol: TCP }
          sun-t2: { port: 47989, protocol: TCP }
          sun-t3: { port: 48010, protocol: TCP }
          sun-u1: { port: 47998, protocol: UDP }
          sun-u2: { port: 47999, protocol: UDP }
          sun-u3: { port: 48000, protocol: UDP }
          sun-u4: { port: 48002, protocol: UDP }
          sun-u5: { port: 48010, protocol: UDP }
    # route:
    #   app:
    #     hostnames:
    #       - "{{ .Release.Name }}.janpuc.com"
    #     parentRefs:
    #       - name: envoy-internal
    #         namespace: network
    #         sectionName: https
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /home/default
      library-nfs:
        type: nfs
        server: bigmouth.internal
        path: /mnt/Vault/Media/Games
        globalMounts:
          - path: /mnt/nfs-games
      input:
        type: hostPath
        hostPath: /dev/input
        globalMounts:
          - path: /dev/input
      uinput:
        type: hostPath
        hostPath: /dev/uinput
        globalMounts:
          - path: /dev/uinput
      dri:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri
      shm:
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        globalMounts:
          - path: /dev/shm
