---
- Bookmarks:
    - Mail:
        - icon: si-protonmail
          href: https://mail.proton.me/
    - YouTube:
        - icon: si-youtube
          href: https://youtube.com/
    - Calendar:
        - icon: si-googlecalendar
          href: https://calendar.google.com/
    - Maps:
        - icon: si-googlemaps
          href: https://maps.google.com/
    - GitHub:
        - icon: si-github
          href: https://github.com/
    - Home Ops:
        - icon: mdi-home-edit-outline
          href: https://github.com/janpuc/home-ops
    - Nix:
        - icon: si-nixos
          href: https://github.com/janpuc/nix-config
    - Deepseek:
        - icon: mdi-chat-processing-outline
          href: https://chat.deepseek.com/
- Random:
    - Simple Icons:
        - icon: si-simpleicons
          href: https://simpleicons.org/
    - Material Design Icons:
        - icon: si-materialdesignicons
          href: https://pictogrammers.com/library/mdi/
    - Open Signups:
        - icon: mdi-pirate
          href: https://www.reddit.com/r/OpenSignups/
    - Onedr0p:
        - icon: si-kubernetes
          href: https://github.com/onedr0p/home-ops
