---
- Bookmarks:
    - Mail:
        - icon: si-protonmail
          href: https://mail.proton.me/
    - YouTube:
        - icon: si-youtube
          href: https://youtube.com/
    - Calendar:
        - icon: si-googlecalendar
          href: https://calendar.google.com/
    - GitHub:
        - icon: si-github
          href: https://github.com/
    - HomeOps:
        - icon: mdi-home-edit-outline
          href: https://github.com/janpuc/home-ops
    - Nix:
        - icon: si-nixos
          href: https://github.com/janpuc/nix-config
    - Deepseek:
        - icon: mdi-chat-processing-outline
          href: https://chat.deepseek.com/
- Random:
    - SimpleIcons:
        - icon: si-simpleicons
          href: https://simpleicons.org/
    - MaterialDesignIcons:
        - icon: si-materialdesignicons
          href: https://pictogrammers.com/library/mdi/
    - OpenSignups:
        - icon: mdi-pirate
          href: https://www.reddit.com/r/OpenSignups/
