---
title: Home
theme: dark
statusStyle: dot
useEqualHeights: true
layout:
  Bookmarks:
    style: row
    columns: 5
    iconsOnly: true
  Calendar:
    style: columns
  Selfhosted:
    style: row
    columns: 3
  Downloads:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 2
  Security:
    style: row
    columns: 2
  Storage:
    style: row
    columns: 2
  Observability:
    style: row
    columns: 3
  Misc:
    style: row
    columns: 3
