---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: janpuc-com
spec:
  dnsNames:
    - janpuc.com
    - "*.janpuc.com"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: janpuc-com-tls
  usages:
    - digital signature
