---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: lan
  namespace: kube-system
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "lan",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp2s0f0",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.69.0/24",
            "rangeStart": "192.168.69.30",
            "rangeEnd": "192.168.69.35",
            "gateway": "192.168.69.1",
            "routes": [
              {"dst": "0.0.0.0/0", "gw": "192.168.69.1"}
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
