---
authentication_backend:
  ldap:
    address: ldap://lldap.default.svc.cluster.local:3890
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: '{{ env "LLDAP_LDAP_BASE_DN" }}'
    additional_users_dn: ou=people
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    user: 'uid={{ env "LLDAP_LDAP_USER_DN" }},ou=people,{{ env "LLDAP_LDAP_BASE_DN" }}'
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn
  password_reset:
    disable: true
  refresh_interval: 1m

session:
  name: authelia-home-ops
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: authelia_session
      domain: janpuc.com
      authelia_url: https://auth.janpuc.com
      default_redirection_url: https://home.janpuc.com

storage:
  local:
    path: '/config/db.sqlite3'

notifier:
  disable_startup_check: true

duo_api:
  disable: true

access_control:
  ## Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
  ## resource if there is no policy to be applied to the user.
  default_policy: two_factor
  networks:
    - name: private
      networks: [10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16]
  rules:
    # bypass Authelia WAN + LAN
    - domain:
        - auth.janpuc.com
      policy: bypass
    # One factor auth for LAN
    - domain:
        - "*.janpuc.com"
      policy: one_factor
      subject: [group:admins, group:users]
      networks:
        - private

identity_providers:
  oidc:
    jwks:
      - key: |
          {{ env "OIDC_JWKS_KEY" | mindent 10 "|" | msquote }}
    cors:
      endpoints: [authorization, token, revocation, introspection]
      allowed_origins_from_client_redirect_uris: true
    claims_policies:
      kavita:
        id_token:
          - "email"
          - "email_verified"
          - "groups"
    clients:
    # Genereate client_secret
    # https://www.authelia.com/integration/openid-connect/frequently-asked-questions/#how-do-i-generate-a-client-identifier-or-client-secret
      - client_name: jellyfin
        client_id: jellyfin
        client_secret: '{{ env "JELLYFIN_OAUTH_DIGEST" }}'
        public: false
        authorization_policy: two_factor
        require_pkce: true
        pkce_challenge_method: S256
        pre_configured_consent_duration: 1y
        scopes: [openid, profile, groups]
        redirect_uris: [ "https://jellyfin.janpuc.com/sso/OID/redirect/authelia"]
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post
      - client_name: kavita
        client_id: kavita
        client_secret: '{{ env "KAVITA_OAUTH_DIGEST" }}'
        public: false
        authorization_policy: two_factor
        response_types: [code]
        pre_configured_consent_duration: 1y
        scopes: [openid, email, profile, groups, roles, offline_access]
        redirect_uris: [ "https://comics.janpuc.com/signin-oidc", "https://comics.janpuc.com/signout-callback-oidc" ]
        token_endpoint_auth_method: client_secret_post
        grant_types: [authorization_code, refresh_token]
      - client_name: qui
        client_id: qui
        client_secret: '{{ env "QUI_OAUTH_DIGEST" }}'
        public: false
        authorization_policy: two_factor
        require_pkce: true
        pkce_challenge_method: S256
        pre_configured_consent_duration: 1y
        scopes: [openid, email, profile, groups]
        redirect_uris: [ "https://qui.janpuc.com/api/auth/oidc/callback"]
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post
