---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: komf-secret
    template:
      data:
        KOMF_KAVITA_API_KEY: "{{ .KOMF_KAVITA_API_KEY }}"
  dataFrom:
    - extract:
        key: komf
