---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./bhplus/ks.yaml
  - ./authelia/ks.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homepage/ks.yaml
  - ./jellyfin/ks.yaml
  - ./kavita/ks.yaml
  - ./komf/ks.yaml
  - ./lldap/ks.yaml
  - ./notifier/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
  - ./suwayomi/ks.yaml
  - ./thelounge/ks.yaml
  - ./tqm/ks.yaml
  # - ./watchstate/ks.yaml
