---
clients:
  qb:
    create_tags_upfront: false
    download_path: /media/Downloads/qbittorrent/complete
    enabled: true
    filter: default
    type: qbittorrent
    url: http://qbittorrent.default.svc.cluster.local

filters:
  default:
    MapHardlinksFor:
      - retag

    ignore:
      - IsTrackerDown()
      - Downloaded == false && !IsUnregistered()
      - SeedingHours < 26 && !IsUnregistered()

    remove:
      - IsUnregistered()
      - HasAnyTag("public") && Ratio > 2.0
      - (
          HasAnyTag(
            "site:DPS", "site:IHD", "site:PTT", "site:RAG", "site:SA",
            "site:TLPL", "site:YO"
          ) &&
          Ratio > 3.0
        )
        )
      - HasAnyTag("not-linked") && SeedingDays > 24

    tag:
      - { name: activity:1d,   update: ['LastActivityDays < 7'] }
      - { name: activity:7d,   update: ['LastActivityDays >= 7 && LastActivityDays < 14'] }
      - { name: activity:14d,  update: ['LastActivityDays >= 14 && LastActivityDays < 30'] }
      - { name: activity:30d,  update: ['LastActivityDays >= 30 && LastActivityDays < 180'] }
      - { name: activity:180d, update: ['LastActivityDays >= 180'] }
      - { name: added:1d,      update: ['AddedDays < 7'] }
      - { name: added:7d,      update: ['AddedDays >= 7 && AddedDays < 14'] }
      - { name: added:14d,     update: ['AddedDays >= 14 && AddedDays < 30'] }
      - { name: added:30d,     update: ['AddedDays >= 30 && AddedDays < 180'] }
      - { name: added:180d,    update: ['AddedDays >= 180'] }
      - { name: not-linked,    update: ['HardlinkedOutsideClient == false && Label in ["sonarr", "radarr"]'] }
      - { name: public,        update: ['IsPrivate == false'] }
      - { name: site:DPS,      update: ['TrackerName == "darkpeers.org"'] }
      - { name: site:IHD,      update: ['TrackerName == "infinityhd.net"'] }
      - { name: site:PTT,      update: ['TrackerName == "polishtorrent.top"'] }
      - { name: site:RAG,      update: ['TrackerName == "rastastugan.org"'] }
      - { name: site:SA,       update: ['TrackerName == "speedapp.io"'] }
      - { name: site:TLPL,     update: ['TrackerName == "torrentleech.pl"'] }
      - { name: site:YO,       update: ['TrackerName == "yoinked.org"'] }
      - { name: tracker-down,  update: ['IsTrackerDown()'] }
      - { name: unregistered,  update: ['IsUnregistered()'] }
