---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: satisfactory-data
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: satisfactory-data
    template:
      data:
        lb_nsg_id: "{{ .lb_nsg_id }}"
  dataFrom:
    - extract:
        key: oke-data
