---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netronome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netronome-secret
    template:
      data:
        NETRONOME_SESSION_SECRET: "{{ .NETRONOME_SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: netronome
