---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: polish-language-radarr-configmap
    files:
      - polish-language-radarr.json=./resources/polish-language-radarr.json
  - name: polish-language-sonarr-configmap
    files:
      - polish-language-sonarr.json=./resources/polish-language-sonarr.json
  - name: recyclarr-configmap
    files:
      - recyclarr.yml=./resources/recyclarr.yml
  - name: settings-configmap
    files:
      - settings.yml=./resources/settings.yml
generatorOptions:
  disableNameSuffixHash: true
