---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    template:
      data:
        # default NS
        HOMEPAGE_VAR_AUTOBRR_API_KEY: "{{ .AUTOBRR_API_KEY }}"
        HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_HASS_API_KEY: "{{ .HASS_API_KEY }}"
        HOMEPAGE_VAR_JELLYFIN_API_KEY: "{{ .JELLYFIN_API_KEY }}"
        HOMEPAGE_VAR_KAVITA_API_KEY: "{{ .KAVITA_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SEERR_API_KEY: "{{ .SEERR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        # observability NS
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_PASSWORD }}"
        # volsync-system NS
        HOMEPAGE_VAR_KOPIA_USERNAME: "{{ .KOPIA_USERNAME }}"
        HOMEPAGE_VAR_KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
  dataFrom:
    - extract:
        key: homepage
