---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr.default.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      # WEB-1080p
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p
      # Remux-1080p - Anime
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime
    quality_profiles:
      - name: WEB-1080p
    custom_formats:
      # WEB-1080p
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p
      # Remux-1080p - Anime
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
radarr:
  radarr:
    base_url: http://radarr.default.svc.cluster.local
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_profiles:
      - name: SQP-1 (2160p)
      - name: SQP-1 (2160p) [Polish]
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
          until_score: 10000
        min_format_score: 1000
        score_set: sqp-1-2160p
        quality_sort: top
        qualities:
          - name: Bluray-2160p
          - name: WEB-2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
          - name: Bluray|WEB-1080p
            qualities:
              - Bluray-1080p
              - WEBDL-1080p
              - WEBRip-1080p
              - WEBDL-720p
              - WEBRip-720p
          - name: Bluray-720p
    include:
      # SQP-1 (2160p)
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-quality-profile-sqp-1-2160p-default
      - template: radarr-custom-formats-sqp-1-2160p
      # Remux-1080p - Anime
      - template: radarr-quality-definition-anime
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime
    custom_formats:
      # SQP-1 (2160p)
      - trash_ids:
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: 0
          - name: SQP-1 (2160p) [Polish]
            score: 0
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 (2160p)
          - name: SQP-1 (2160p) [Polish]
      - trash_ids:
          - polish-language-radarr           # Polish
        assign_scores_to:
          - name: SQP-1 (2160p) [Polish]
      # Remux-1080p - Anime
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
