---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr.default.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      # WEB-1080p
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p
      # Remux-1080p - Anime
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime
    quality_profiles:
      - name: WEB-1080p
    custom_formats:
      # WEB-1080p
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p
      # Remux-1080p - Anime
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
radarr:
  radarr:
    base_url: http://radarr.default.svc.cluster.local
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_profiles:
      - name: SQP-1 (2160p)
      - name: SQP-1 (2160p) [Polish]
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
          until_score: 10000
        min_format_score: 1000
        score_set: sqp-1-2160p
        quality_sort: top
        qualities:
          - name: Bluray-2160p
          - name: WEB-2160p
            qualities:
              - WEBDL-2160p
              - WEBRip-2160p
          - name: Bluray|WEB-1080p
            qualities:
              - Bluray-1080p
              - WEBDL-1080p
              - WEBRip-1080p
              - WEBDL-720p
              - WEBRip-720p
          - name: Bluray-720p
    include:
      # SQP-1 (2160p)
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-quality-profile-sqp-1-2160p-default
      - template: radarr-custom-formats-sqp-1-2160p
      # Remux-1080p - Anime
      - template: radarr-quality-definition-anime
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime
    custom_formats:
      # SQP-1 (2160p)
      - trash_ids:
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: SQP-1 (2160p)
            score: 0
          - name: SQP-1 (2160p) [Polish]
            score: 0
      - trash_ids:
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 (2160p)
          - name: SQP-1 (2160p) [Polish]
      - trash_ids:
          - polish-language-radarr           # Polish
        assign_scores_to:
          - name: SQP-1 (2160p) [Polish]
      - trash_ids:
          # Audio
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
          - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          - 3cafb66171b47f226146a0770576870f # TrueHD
          - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          - e7c2fcae07cbada050a0af3357491d7b # PCM
          - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          - 185f1dd7264c4562b9022d963ac37424 # DD+
          - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          - 240770601cc226190c367ef59aba7463 # AAC
          - c2998bd0d90ed5621d8df281e839436e # DD
          # Unified HDR + DV (w/o HDR fallback)
          - 493b6d1dbec3c3364c59d7607f7e3405 # HDR
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (w/o HDR fallback)
          # HQ Release Groups
          - 5153ec7413d9dae44e24275589b5e944 # BHDStudio
          - 7a0d1ad358fee9f5b074af3ef3f9d9ef # hallowed
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - 4d74ac4c4db0b64bff6ce0cffef99bf0 # UHD Bluray Tier 01
          - a58f517a70193f8e578056642178419d # UHD Bluray Tier 02
          - e71939fae578037e7aed3ee219bbe7c1 # UHD Bluray Tier 03
          # Misc
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          - 5caaaa1c08c1742aa4342d8c4cc463f2 # Repack3
          # Unwanted
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - e6886871085226c3da1830830146846c # Generated Dynamic HDR
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
          - 0a3f082873eb454bde444150b70253cc # Extras
          - 712d74cd88bceb883ee32f773656b1f5 # Sing-Along Versions
          - a5d148168c4506b55cf53984107c396e # Hi10P
          - cae4ca30163749b891686f95532519bd # AV1
          # Optional
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
          # Resolution
          - 820b09bb9acbfde9c35c71e0e565dad8 # 1080p
          - b2be17d608fc88818940cd1833b0b24c # 720p
          # Streaming Services
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
          - 2a6039655313bf5dab1e43523b62c374 # MA
        assign_scores_to:
          - name: SQP-1 (2160p) [Polish]
      - trash_ids:
          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - e0ec9672be6cac914ffad34a6b077209 # iT
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
        assign_scores_to:
          - name: SQP-1 (2160p) [Polish]
            score: 0
      # Remux-1080p - Anime
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0
