---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/settings-schema.json
resource_providers:
  - name: polish-language-radarr
    type: custom-formats
    path: /config/custom-formats/radarr
    service: radarr
  - name: polish-language-sonarr
    type: custom-formats
    path: /config/custom-formats/sonarr
    service: sonarr
